var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   o            ",
   "                                                    o             xxx           ",
   "                                                   xx            xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx      xx  ",
   "  xx                               x!x!x                          xvx        x  ",
   "  x                           o  x                      o                    x  ",
   "  x                    o                     o     x                         x  ",
   "  x            o             xx                                              x  ",
   "  x                  xxxxx!!!xx         x!!!xxxxx                          % x  ",
   "  x          xxxx!!!!x   x!!!xx        xx                                    x  ",
   "  x  @       x  x!!!!x   x!!!xx       xx  o                   x      oxxxxx  x  ",
   "  xxxxxxxxxxxx  xxxxxx   xxxxxx   xxxxxxxxxxxxxxxxxxx       xxxxx!!xxxxxxxxxxx  ",
   "                              x   x                 x!!!!!!!x                   ",
   "                              x!!!x                 x!!!!!!!x                   ",
   "                              x!!!x                 x!!!!!!!x                   ",
   "                              xxxxx                 xxxxxxxxx                   ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                               oo        xxx     xxx                             ",
   "                                             xxxxxx        x     x                               ",
   "                                               /           x     x    x!    !x                   ",
   "                                      o                    x     x    x!    !x                   ",
   "                                      x                    x   o x    x!  o !x                   ",
   "                                                           x   xxx    x-     x                   ",
   "                                                /          x     x    x!    !x                   ",
   "                                             xxxxxx        x-    x    x!    !x                   ",
   "                             o                 xx          x     x    x!    !x                   ",
   "                                               xx          xo    x    x     -x                   ",
   "                                               xx          xxx   x    x!    !x                   ",
   "                                               xx          x     x    x!  o !x                   ",
   "                                         xxx   xx          x    -x    x!    !x                   ",
   "               o                          x    xx          x     x    x-     x                   ",
   "              xxx       xx       xx       x    xx          x    ox    x!    !x                   ",
   "         o     x         x       x        x    xx          x   xxx    x!    !x                   ",
   "        xxx    x         x$$$$$$$x        x    xx          x     x    x!    !x   x   x   x       ",
   "  @      x     x         xxxxxxxxx        x    xx          x     x    x!    !xxxx/xxx xxx/xxxx   ",
   "  xxx    x$$$$$x                          x    xx          x     x    x!    xx             o x   ",
   "   x     x$$$$$x                          x    xx          x ooo x    x!                     x   ",
   "   x$$$$$x$$$$$x                          x    xx          xxxxxxx    x!  o        o / o     x   ",
   "$$$x$$$$$x$$$$$x                          x    xx                     xxxxxxxxxxxxxxxxxxxxxxxx   ",
   "$$$x$$$$$x$$$$$x                          x    xx                                                "],
  ["                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                 ",
   "  x!!!!!!!!!!!!!!!!!!!!!!x           /     x                                 ",
   "  x!!!!!x!!!!!v!!v!!v!!v!x                 x                                 ",
   "  x!!!xx                                   x                                 ",
   "  x!!xx                                  * x                                 ",
   "  x!x                                 xxxxxx                                 ",
   "  x!x                                  /  /x                                 ",
   "  x!x       xxxxxxxxxxxxxxxxx              x                                 ",
   "  x!x       |  xxxxxx       x              x                                 ",
   "  x!x           xxxxx       x       /      x                            xxx  ",
   "  x!x*          =xxxx       xxxxxxxxxxx    x                              x  ",
   "  xxxxx           xxx       x              x                              x  ",
   "      x            xx       x              x                x             x  ",
   "  xxxxx             x       x              x               $x$            x  ",
   "  x                 x       x   -xxxxxxxxxxx              !!x!!           x  ",
   "  x                 x       x                          x $$$x$$$          x  ",
   "  x!!!!!   xxx=     x       x                          x!!!!x!!!!         x  ",
   "  xxxxxx            x       x                         $x$$$$x$$$$$        x  ",
   "       x        =xxxx       xxxxxx!xxxxx!xxx         !!x!!!!x!!!!!!       x  ",
   "  xxxxxx            x                      x        $$$x$$$$x$$$$$$$      x  ",
   "  x                 x                      x      x!!!!x!!!!x!!!!!!!!   * x  ",
   "  x                 x                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x                 x                                                        ",
   "  x          =x     x                                                        ",
   "  x   @       x     x                                                        ",
   "  x   xx   *  x     x                                                        ",
   "  x   xx   x  x     x                                                        ",
   "  x   xx   x  x     x                                                        ",
   "  x   xx / x/ x     x                                                        ",
   "  x$$$xx$$$x$$x$$$$$x                                                        ",
   "  xxxxxxxxxxxxxxxxxxxx                                                       ",
   "                                                                             ",
   "                                                                             "],
  ["                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                                                                                            ",
   "                        xx   xx   xxxxxx   xx  xx      xx    x    xx   xx   xxxx     xx     ",
   "                        xx   xx   xxxxxx   xx  xx      xx   xxx   xx   xx   xxxxx    xx     ",
   "                        xx   xx   xx  xx   xx  xx      xx  xx xx  xx   xx   xx xx    xx     ",
   "                        xxxxxxx   xx  xx   xx  xx      xx  xx xx  xx   xx   xx xxx   xx     ",
   "  xx                    xxxxxxx   xx  xx   xx  xx      xx xx   xx xx   xx   xx  xxx  xx     ",
   "  x                       xxx     xx  xx   xx  xx      xxxx     xxxx   xx   xx   xxx xx     ",
   "  x                       xxx     xxxxxx   xxxxxx      xxxx     xxxx   xx   xx    xxxxx     ",
   "  x                       xxx     xxxxxx   xxxxxx      xxx       xxx   xx   xx     xxxx     ",
   "  x                                                                                         ",
   "  x                                                                                         ",
   "  x  @                                                                                      ",
   "  xxxxxxx                                                                                   ",
   "        x                                                                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                            ",
   "                                                                                            "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
